### PR TITLE
Initial support for `#[derive(Visit)]`

### PR DESCRIPTION
**Pull request by toyboot4e**
# About

This PR adds experimentals supports for `#[derive(Visit)]`

## How to use

```rust
use rg3d::core::visitor::prelude::*;
// or: use rg3d_core::visitor::prelude::*;

#[derive(Visit)]
pub struct MyCoolStruct { .. }
```

## Supported types

* `struct UnitStruct;`
* `struct TupleFields(f32, f32);`
* `struct NamedFields { a: f32, b: f32 }`
* `enum ComplexEnum { UnitVariant, TupleVariant(f32, 32), NamedVariant { a: f32,  b: f32 } }`

Generics are also considered. For example, `struct Generics<T> { items: Vec<T> }` implements `Visit` with `where Vec<T>: Visit` clause.

## Note

Please run `cargo expand --tests basic` to know what the `Visit` implementations are like :)

# Old WIP comments

<details>
  <summary>Old comments</summary>

## Progress

* [x] Struct with named fields

<details>
  <summary>Example</summary>

```rust
// imports both the trait and the derive macro
use rg3d::core::visitor::Visit;

#[derive(Visit)]
struct NamedFields {
    a: f32,
    snake_case: u32,
}
```

Part of `cargo expand --test basic`:

```rust
impl rg3d::core::visitor::Visit for NamedFields {
    fn visit(
        &mut self,
        name: &str,
        visitor: &mut rg3d::core::visitor::Visitor,
    ) -> rg3d::core::visitor::VisitResult {
        visitor.enter_region(name)?;
        self.a.visit("A", visitor)?;
        self.snake_case.visit("SnakeCase", visitor)?;
        visitor.leave_region()
    }
}
```

</details>

* [x] Implemeint `#[visit(skip)]` field attribute (using [darling](https://github.com/TedDriggs/darling))

<details>
  <summary>Example</summary>

```rust
use rg3d::core::visitor::Visit;

#[derive(Debug, Clone, Default, PartialEq, Visit)]
struct SkipAttr {
    visited: f32,
    #[visit(skip)]
    skipped: u32,
}
```

Part of `cargo expand --test basic`:

```rust
impl rg3d::core::visitor::Visit for SkipAttr {
    fn visit(
        &mut self,
        name: &str,
        visitor: &mut rg3d::core::visitor::Visitor,
    ) -> rg3d::core::visitor::VisitResult {
        visitor.enter_region(name)?;
        self.visited.visit("Visited", visitor)?;
        visitor.leave_region()
    }
}
```

</details>
 
* [x] Support plain enums

<details>
  <summary>Example</summary>

```rust
#[derive(Debug, Clone, PartialEq, Eq, Hash, Visit)]
enum PlainEnum {
    A,
    B,
    C,
}
```

Part of `cargo expand --test basic`:

```rust
impl rg3d::core::visitor::Visit for PlainEnum {
    fn visit(
        &mut self,
        name: &str,
        visitor: &mut rg3d::core::visitor::Visitor,
    ) -> rg3d::core::visitor::VisitResult {
        visitor.enter_region(name)?;
        let mut id = self.clone() as u32;
        id.visit("Id", visitor)?;
        if visitor.is_reading() {
            *self = match id {
                id if id == PlainEnum::A as u32 => PlainEnum::A,
                id if id == PlainEnum::B as u32 => PlainEnum::B,
                id if id == PlainEnum::C as u32 => PlainEnum::C,
                _ => {
                    return Err(rg3d::core::visitor::VisitError::User({
                        let res = ::alloc::fmt::format(::core::fmt::Arguments::new_v1(
                            &["Invalid ID for enum `", "`: "],
                            &match (&"PlainEnum", &id) {
                                (arg0, arg1) => [
                                    ::core::fmt::ArgumentV1::new(arg0, ::core::fmt::Display::fmt),
                                    ::core::fmt::ArgumentV1::new(arg1, ::core::fmt::Display::fmt),
                                ],
                            },
                        ));
                        res
                    }))
                }
            }
        }
        visitor.leave_region()
    }
}
```

</details>

* [x] Support one-of-the-types enums (upcasting enums)

<details>
  <summary>Example</summary>

```rust
#[derive(Debug, Clone, PartialEq, Visit)]
enum OneOfTheTypes {
    NamedFields(NamedFields),
    PlainEnum(PlainEnum),
    U32(u32),
}
```

Part of `cargo expand --test basic`:

```rust
impl rg3d::core::visitor::Visit for OneOfTheTypes {
    fn visit(
        &mut self,
        name: &str,
        visitor: &mut rg3d::core::visitor::Visitor,
    ) -> rg3d::core::visitor::VisitResult {
        fn id(me: &OneOfTheTypes) -> u32 {
            match me {
                OneOfTheTypes::NamedFields(_) => 0u32,
                OneOfTheTypes::PlainEnum(_) => 1u32,
                OneOfTheTypes::U32(_) => 2u32,
                _ => ::core::panicking::panic_fmt(::core::fmt::Arguments::new_v1(
                    &["internal error: entered unreachable code: "],
                    &match (&"Unable to get ID from enum variant",) {
                        (arg0,) => [::core::fmt::ArgumentV1::new(
                            arg0,
                            ::core::fmt::Display::fmt,
                        )],
                    },
                )),
            }
        }
        fn from_id(id: u32) -> std::result::Result<OneOfTheTypes, String> {
            match id {
                id if id == 0u32 => Ok(OneOfTheTypes::NamedFields(Default::default())),
                id if id == 1u32 => Ok(OneOfTheTypes::PlainEnum(Default::default())),
                id if id == 2u32 => Ok(OneOfTheTypes::U32(Default::default())),
                _ => Err({
                    let res = ::alloc::fmt::format(::core::fmt::Arguments::new_v1(
                        &["Unknown ID for type `", "`: `", "`"],
                        &match (&"OneOfTheTypes", &id) {
                            (arg0, arg1) => [
                                ::core::fmt::ArgumentV1::new(arg0, ::core::fmt::Display::fmt),
                                ::core::fmt::ArgumentV1::new(arg1, ::core::fmt::Display::fmt),
                            ],
                        },
                    ));
                    res
                }),
            }
        }
        visitor.enter_region(name)?;
        let mut id = id(self);
        id.visit("KindId", visitor)?;
        if visitor.is_reading() {
            *self = from_id(id)?;
        }
        match self {
            OneOfTheTypes::NamedFields(v) => v.visit("Data", visitor)?,
            OneOfTheTypes::PlainEnum(v) => v.visit("Data", visitor)?,
            OneOfTheTypes::U32(v) => v.visit("Data", visitor)?,
        }
        visitor.leave_region()
    }
}
```

</details>

## TODOs

* [ ] Polish
As in the first comment in this PR, we can support more types and make the implementation simpler.

* [ ] `#[visit(rename = ..)]` attribute
* [ ] Attribute macros on enum variant fields1

## Problems

* The `Visit` macro is exposed in `rg3d-core::visitor`, but it requires `rg3d` to be in scope of user (since it implements `rg3d::core::visitor::Visit`). If anyone uses `rg3d-core` as a stand-alone crate, it doesn't make sense.

* Replacing existing `Visit` implementation with the derive macro may break the byte data compatibility (if I understand correctly).
  * `#[derive(Visit)]` calls struct fields in the order of field declarations.
  * Each data may be given different name between before/after using `#[derive(Visit)]`.

## Implementation problems

* I'm using `syn` types for enums because I couldn't figure out how to use `darling` for enums.

</details>

### CODE REVIEW

**Comment by toyboot4e** [comment]
The derive macro is becoming practical, as seen in the examples above. 
Let me ask some questions to let it be more usable and polished :)

# Detailed questions

1. In StationIapetus, `enum Actor` names their id as `"KindId"`. But can we always use `"Id"` for enum IDs?

2. `enum PlainEnum { A = 10, B = 20 }` uses `PlainEnum::A as u32` as their ID (for example). Can we always use the variant index as their ID (so the ID of `PlainEnum::A` is zero, the ID of `PlainEnum::B` is one).

# `impl Visit` questions

How should we implement `Visit` for these types?

1. Tuple struct

I didn't find such type in `rg3d` or StationIapetus. Let me know if there's one.

```rust
pub struct TupleStruct(u32, i32);
```

<details>
<summary>Idea</summary>

```rust
impl Visit for TupleStruct {
    fn visit(
        &mut self,
        name: &str,
        visitor: &mut rg3d::core::visitor::Visitor,
    ) -> VisitResult {
        visitor.enter_region(name)?;
        self.0.visit("Data0", visitor)?;
        self.1.visit("Data1", visitor)?;
        visitor.leave_legion()
    }
}
```

</details>

2. Enum variants with named fields

```rust
pub enum ComplexEnum {
    Unit,
    Tuple(u32, f32),
    NamedFields {
        a: f32,
        b: u32,
    },
}
```

<details>
<summary>Idea</summary>

```rust
impl Visit for ComplexEnum {
    fn visit(
        &mut self,
        name: &str,
        visitor: &mut rg3d::core::visitor::Visitor,
    ) -> VisitResult {
        fn id(&ComplexEnum) -> u32 { .. }
        fn from_id(id: u32) -> Result<Self, String> { .. }

        visitor.enter_region(name)?;

        let id = id(self);
        id.visit("Id", visitor)?;

        if visitor.is_reading() {
            *self = match id {
                0 => ComplexEnum::Unit,
                1 => ComplexEnum::Tuple(Default::default(), Default::default()),
                2 => ComplexEnum::NamedFields {
                    a: Default::default(),
                    b: Default::default(),
                }
            }
        }

        match self {
            ComplexEnum::Unit => {}
            ComplexEnum::Tuple(x0, x1) => {
                x0.visit("Data0", visitor)?;
                x1.visit("Data1", visitor)?;
            }
            ComplexEnum::NamedFields { a, b } => {
                a.visit("a", visitor)?;
                b.visit("b", visitor)?;
            }
        }

        visitor.leave_legion()
    }
}
```

**Comment by mrDIMAS** [comment]
>     * The `Visit` macro is exposed in `rg3d-core::visitor`, but it requires `rg3d` to be in scope of user (since it implements `rg3d::core::visitor::Visit`). If anyone uses `rg3d-core` as a stand-alone crate, it doesn't make sense.

I think only possible solution for that is to remove `rg3d::core::visitor::` prefix and use `::Visit`, `::Visitor` etc. directly. A user then will only need to import these types/traits.

**Comment by mrDIMAS** [comment]
> * `#[derive(Visit)]` calls struct fields in the order of field declarations.
> 
> * Each data may be given different name between before/after using `#[derive(Visit)]`.

First is not a problem, because visitor is order-independent, latter might be a problem if I was not consistent in some places.

**Comment by mrDIMAS** [comment]
>     1. But can we always use `"Id"` for enum ID names?

Yeah, `Id` is nice.



>     2\. `enum PlainEnum { A = 10, B = 20 }` uses `PlainEnum::A as u32` as their ID (for example). Can we always use the variant index as their ID (so the ID of `PlainEnum::A` is zero, the ID of `PlainEnum::B` is one, and the derive macro impl will be simpler).

It should be good, yes. One problem with that is that when one will change numeric value of variant and it will break data compatibility.



> How should we implement `Visit` for these types?

Your solutions should do the job. In general every implementation details are up to you really, for me they're good.

And huge thanks for this PR, I was thinking about implementing this myself but was too busy with other stuff. Great job!

**Comment by mrDIMAS** [comment]
Btw, I can't wait this to be merged because I'm adding 2D scenes support and don't want to write visit boilerplate code anymore 😄

**Comment by toyboot4e** [comment]
> In general every implementation details are up to you really, for me they're good.

Ok, I stopped worrying about the byte data representation!

> Btw, I can't wait this to be merged because I'm adding 2D scenes support and don't want to write visit boilerplate code anymore 😄

Cool.. you motivated me to do this immediately ;)

---

So I extended `#[derive(Visit)]` to support various types:

<details>
    <summary>Example</summary>

```rust
impl Visit for ComplexEnum {
    fn visit(&mut self, name: &str, visitor: &mut Visitor) -> VisitResult {
        visitor.enter_region(name)?;
        let mut id = id(self);
        id.visit("Id", visitor)?;
        if visitor.is_reading() {
            *self = from_id(id)?;
        }
        match self {
            ComplexEnum::UnitVariant => {}
            ComplexEnum::Tuple(f0, f1) => {
                f0.visit("0", visitor)?;
                f1.visit("1", visitor)?;
            }
            ComplexEnum::NamedFields { a, b } => {
                a.visit("A", visitor)?;
                b.visit("B", visitor)?;
            }
        }
        return visitor.leave_region();
        fn id(me: &ComplexEnum) -> u32 {
            match me {
                ComplexEnum::UnitVariant => 0u32,
                ComplexEnum::Tuple(_, _) => 1u32,
                ComplexEnum::NamedFields { .. } => 2u32,
                _ => ::core::panicking::panic_fmt(::core::fmt::Arguments::new_v1(
                    &["internal error: entered unreachable code: "],
                    &match (&"Unable to get ID from enum variant",) {
                        (arg0,) => [::core::fmt::ArgumentV1::new(
                            arg0,
                            ::core::fmt::Display::fmt,
                        )],
                    },
                )),
            }
        }
        fn from_id(id: u32) -> std::result::Result<ComplexEnum, String> {
            match id {
                id if id == 0u32 => Ok(ComplexEnum::UnitVariant),
                id if id == 1u32 => Ok(ComplexEnum::Tuple(Default::default(), Default::default())),
                id if id == 2u32 => Ok(ComplexEnum::NamedFields {
                    a: Default::default(),
                    b: Default::default(),
                }),
                _ => Err({
                    let res = ::alloc::fmt::format(::core::fmt::Arguments::new_v1(
                        &["Unknown ID for type `", "`: `", "`"],
                        &match (&"ComplexEnum", &id) {
                            (arg0, arg1) => [
                                ::core::fmt::ArgumentV1::new(arg0, ::core::fmt::Display::fmt),
                                ::core::fmt::ArgumentV1::new(arg1, ::core::fmt::Display::fmt),
                            ],
                        },
                    ));
                    res
                }),
            }
        }
    }
}
```
</details>

Notes:

* I couldn't keep the implementation simple.
* Feel free to replace this implementation later :)
* Feel free to work with me with the derive macro at anytime :)

**Comment by toyboot4e** [comment]
Also, feel free to squash the commits :)

**Comment by toyboot4e** [comment]
I forgot to support `enum GenericEnum<T>`. Finally it's ready  🎉

**Pull request merged**
